issue: HPCINFRA-1321 Switch cppcheck to a docker
Mellanox/libxlio pull request #103
Opened 2024-03-05 13:34 UTC by vialogi

## Description
We're going to move static tests from a dedicated server to docker containers to reduce CI timings 

##### What
Switch Cppcheck, Csbuild and Tidy steps of the CI to run in docker containers in a parallel mode

##### Why ?
CI currently takes too long, a majority of the time is consumed by static tests running on a physical machine

## Change type
What kind of change does this PR introduce?
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [X] CI related changes
- [ ] Documentation content changes
- [ ] Tests
- [ ] Other

## Check list
- [ ] Code follows the style de facto guidelines of this project
- [ ] Comments have been inserted in hard to understand places
- [ ] Documentation has been updated (if necessary)
- [ ] Test has been added (if possible)

2024-03-06 09:14 UTC, igor-ivanov commented
it seems that suggested container does not have `cppcheck` tool installed.
```
[2024-03-05T14:27:11.989Z] + echo '[SKIP] cppcheck tool does not exist'
[2024-03-05T14:27:11.989Z] [SKIP] cppcheck tool does not exist
```

Container should include cppcheck, csbuild and tidy the same version as beni09 to avoid extra noises in results.

2024-03-10 07:41 UTC, dpressle requested changes

2024-03-10 07:41 UTC, dpressle commented on .ci/dockerfiles/Dockerfile.rhel8.6
> +ARG MOFED_VER=5.3-1.0.0.1
not used please remove

2024-03-10 07:41 UTC, dpressle commented on .ci/matrix_job.yaml
> +# env:
remove comments

2024-03-10 07:41 UTC, dpressle commented on contrib/jenkins_tests/cppcheck.sh
> +    # set +e
If not needed lets remove

2024-03-11 09:19 UTC, dpressle commented on contrib/jenkins_tests/cppcheck.sh
> +    yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
why its still here? its in the image now

2024-03-12 12:52 UTC, vialogi commented
bot:retest

2024-03-12 15:52 UTC, dpressle approved these changes

2024-03-12 18:45 UTC, merged