Xlio container error
Mellanox/libxlio pull request #171
Opened 2024-06-25 11:25 UTC by BasharRadya

## Description
At startup, XLIO tries to read files in the /proc/sys/net/core/ directory, which can be inaccessible when running in a container (it doesn’t matter whether in privileged mode or not).  In this case, XLIO produces ERROR messages which can be considered as WARNINGs.
##### What
Change error message with warning message when read files from  /proc/sys/net/core/ 
##### Why ?
This breaks CI and blocks the integration with DOCA.

## Change type
What kind of change does this PR introduce?
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Tests
- [ ] Other

## Check list
- [ ] Code follows the style de facto guidelines of this project
- [ ] Comments have been inserted in hard to understand places
- [ ] Documentation has been updated (if necessary)
- [ ] Test has been added (if possible)

2024-06-25 11:26 UTC, swx-jenkins3 commented
Can one of the admins verify this patch?

2024-06-25 12:27 UTC, pasis commented
I would suggest to modify `read_file_to_int()` and `priv_read_file()`. These functions print a message on a failure with the word "ERROR". On the other hand, these functions allow to change log severity and it will be confusing to see a warning or info log with an "ERROR" word.

Please, rephrase those messages with something like this:
 * Couldn't open file ...
 * Couldn't read file ...
 * Couldn't read an integer from file ...
And make sure that all 3 messages contain "(errno %d)".

Regarding commit message:
Remove symbol "#" from the issue number (commit message format convention).
Describe motivation for the change in the commit message.

2024-06-26 07:16 UTC, pasis requested changes

2024-06-26 07:16 UTC, pasis commented on src/core/util/utils.cpp
> +        VLOG_PRINTF(log_level, "Couldn't read an integer from file %s (errno %d %m), we'll use default %d",
Please fix the coding style according to the diff:
```diff
diff --git a/src/core/util/utils.cpp b/src/core/util/utils.cpp
index 4dd82bc81..e16a5ed0d 100644
--- a/src/core/util/utils.cpp
+++ b/src/core/util/utils.cpp
@@ -566,7 +566,8 @@ int read_file_to_int(const char *path, int default_value, vlog_levels_t log_leve
     int value = -1;
     std::ifstream file_stream(path);
     if (!file_stream || !(file_stream >> value)) {
-        VLOG_PRINTF(log_level, "Couldn't read an integer from file %s (errno %d %m), we'll use default %d",
+        VLOG_PRINTF(log_level,
+                    "Couldn't read an integer from file %s (errno %d %m), we'll use default %d",
                     path, errno, default_value);
         return default_value;
     }
```

2024-06-26 07:30 UTC, pasis approved these changes
Need to run CI

2024-06-26 12:15 UTC, dpressle commented
bot:retest

2024-06-26 17:19 UTC, galnoam commented
bot:retest

2024-06-27 05:37 UTC, merged