issue: HPCINFRA-1798 Update code base to clang-format-15
Mellanox/libxlio pull request #200
Opened 2024-07-22 06:43 UTC by pasis

## Description
Update coding style to clang-format-15

## Change type
What kind of change does this PR introduce?
- [ ] Bugfix
- [ ] Feature
- [x] Code style update
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Tests
- [ ] Other

## Check list
- [ ] Code follows the style de facto guidelines of this project
- [ ] Comments have been inserted in hard to understand places
- [ ] Documentation has been updated (if necessary)
- [ ] Test has been added (if possible)

2024-07-22 07:58 UTC, dpressle requested changes
please remove the following commit its not related to this fix
issue: HPCINFRA-1799 - DEBUG BlackDuck failures

2024-07-22 10:30 UTC, pasis commented
> please remove the following commit its not related to this fix issue: HPCINFRA-1799 - DEBUG BlackDuck failures

Done.

2024-07-23 06:22 UTC, dpressle approved these changes

2024-07-23 06:22 UTC, dpressle commented
bot:retest

2024-07-24 10:45 UTC, merged