issue: 4231240 Revive gtest
Mellanox/libxlio pull request #283
Opened 2024-12-31 12:34 UTC by tomerdbz

The gtest suite doesn't run for doca_xlio_vNext.

while the fork related tests will fail
there's no real reason not to run the other tests.

## Description
1. Fixing assumptions in tests
2. tracking latest stable doca as the old tag had a critical bug (crash) that our test suite caught.
3. skipping fork tests.

##### What
gtest suite for doca_xlio_vNext.

##### Why ?
_Justification for the PR. If there is existing issue/bug please reference._

##### How ?
_It is optional but for complex PRs please provide information about the design,
architecture, approach, etc._

## Change type
What kind of change does this PR introduce?
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Tests
- [ ] Other

## Check list
- [ ] Code follows the style de facto guidelines of this project
- [ ] Comments have been inserted in hard to understand places
- [ ] Documentation has been updated (if necessary)
- [ ] Test has been added (if possible)

2025-01-09 13:22 UTC, tomerdbz commented
bot:retest

2025-01-13 10:05 UTC, dpressle commented on contrib/jenkins_tests/gtest.sh
> +gtest_ip_remote=$(ip -f inet addr show eth0 | awk '/inet / {print $2}' | cut -d/ -f1)
This will always exist in k8s environment

2025-01-16 14:08 UTC, tomerdbz commented on contrib/jenkins_tests/gtest.sh
> +gtest_ip_remote=$(ip -f inet addr show eth0 | awk '/inet / {print $2}' | cut -d/ -f1)
changed according to dpressle comment :) Thanks!
"lets put this line only where we set ip addresses for net1/2 (which is also only true for k8s)"

2025-01-17 17:14 UTC, igor-ivanov commented
@tomerdbz it seems that all gtests that do actual connection or data exchange are skipped. It looks as significant degradation in basic verification

2025-01-19 08:50 UTC, galnoam commented
Hi @igor-ivanov, Currently DOCA do not support fork, this is why we suppress the server client test for now in gtest.

2025-01-20 06:58 UTC, dpressle requested changes

2025-01-20 06:58 UTC, dpressle commented on contrib/jenkins_tests/gtest.sh
> +gtest_ip_remote=$(ip -f inet addr show eth0 | awk '/inet / {print $2}' | cut -d/ -f1)
So i think you should move it somewhere after line 34 (the non manual run which is CI run) because its always true there

2025-01-20 07:57 UTC, igor-ivanov commented
> Hi @igor-ivanov, Currently DOCA do not support fork, this is why we suppress the server client test for now in gtest.

does XLIO support NGINX w/o fork?

2025-01-21 06:41 UTC, galnoam commented
> > Hi @igor-ivanov, Currently DOCA do not support fork, this is why we suppress the server client test for now in gtest.
> 
> does XLIO support NGINX w/o fork?

in NGINX we have a master process so grissik did a W/A to make it work.
but without a master process it's not possible.

2025-02-03 12:26 UTC, dpressle requested changes

2025-02-03 12:26 UTC, dpressle commented on contrib/jenkins_tests/gtest.sh
> -rc=$(($rc+$?))
why removed? now you are not collecting this tests rc

2025-02-11 06:33 UTC, tomerdbz commented
Closed as unprioritized

2025-02-11 06:33 UTC, closed without merging