[CI] Coverity snapshots integration
Mellanox/libxlio pull request #89
Opened 2024-01-24 20:17 UTC by vialogi

We'd like to make CI able to post Coverity reports to https://coverity.mellanox.com/
[HPCINFRA-1430](https://jirasw.nvidia.com/browse/HPCINFRA-1430)

2024-01-25 07:52 UTC, dpressle requested changes
I also would like to see link to a test run in the comments

2024-01-25 07:52 UTC, dpressle commented on contrib/jenkins_tests/cov.sh
Do you use shell check? it seems like you are not. for example, variables should be quoted

2024-01-25 07:52 UTC, dpressle commented on contrib/jenkins_tests/cov.sh
We should use bash and not posix (as a team guide line that we want to follow)
if [[ $do_coverity_snapshot = true ]];

2024-01-25 07:52 UTC, dpressle commented on contrib/jenkins_tests/cov.sh
> +
what about failing the job if it didnt work ? like in line 47

2024-01-25 13:38 UTC, vialogi commented
Sample test run:
http://hpc-master.lab.mtl.com:8080/job/LibXLIO-opensource/457/

2024-01-28 06:43 UTC, dpressle requested changes

2024-01-28 06:43 UTC, dpressle commented on contrib/jenkins_tests/cov.sh
> +rc=$(($rc+$?))
It can be meaningless here (when we dont run cov commit for example), should be in the if/fi block

2024-01-29 12:35 UTC, dpressle requested changes

2024-01-29 12:35 UTC, dpressle commented on contrib/jenkins_tests/cov.sh
> +rc=$(($rc+$?))
i dont see the fix ?

2024-01-30 06:13 UTC, dpressle requested changes

2024-01-30 06:13 UTC, dpressle commented on contrib/jenkins_tests/cov.sh
> +rc=$(($rc+$?))
Fix Indentation

2024-01-30 10:11 UTC, merged